services:
  postgres:
   image: postgres
   container_name: postgres
   ports:
     - 5432:5432
   environment:
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - POSTGRES_DB=${POSTGRES_DB}

  app:
    image: party-web-app
    build: .
    container_name: app
    ports:
      - 5259:5259
