// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PartyWebAppServer.Database;

#nullable disable

namespace PartyWebAppServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240530113258_RepourProvidersAndRepoursTable")]
    partial class RepourProvidersAndRepoursTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("PartyWebAppServer.Database.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("RepourProviderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("RepourProviderId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This is the description of Event 1. It is a very cool event in the club.",
                            EndDateTime = new DateTime(2024, 6, 1, 4, 0, 0, 0, DateTimeKind.Utc),
                            LocationId = 1,
                            Name = "Event 1",
                            Price = 1000,
                            RepourProviderId = 1,
                            StartDateTime = new DateTime(2024, 5, 31, 18, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "This is the description of Event 2. It is a very cool event in the pub.",
                            EndDateTime = new DateTime(2024, 6, 2, 4, 0, 0, 0, DateTimeKind.Utc),
                            LocationId = 2,
                            Name = "Event 2",
                            Price = 2000,
                            RepourProviderId = 2,
                            StartDateTime = new DateTime(2024, 6, 1, 18, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        });
                });

            modelBuilder.Entity("PartyWebAppServer.Database.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Budapest, Váci út 1",
                            Name = "Club event 1",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Address = "Budapest, Váci út 2",
                            Name = "Pub event 1",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Address = "Budapest, Váci út 3",
                            Name = "ATM event 1",
                            Type = 2
                        },
                        new
                        {
                            Id = 4,
                            Address = "Budapest, Váci út 4",
                            Name = "Theater event 1",
                            Type = 3
                        },
                        new
                        {
                            Id = 5,
                            Address = "Budapest, Váci út 5",
                            Name = "Museum event 1",
                            Type = 4
                        });
                });

            modelBuilder.Entity("PartyWebAppServer.Database.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("Name")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = 1
                        });
                });

            modelBuilder.Entity("PartyWebAppServer.Database.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<int>("SpentCurrency")
                        .HasColumnType("integer");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer");

                    b.Property<int>("WalletId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("LocationId");

                    b.HasIndex("WalletId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("PartyWebAppServer.Database.Models.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PasswordUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Username");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Username = "admin",
                            BirthDate = new DateTime(1994, 5, 30, 11, 32, 57, 61, DateTimeKind.Utc).AddTicks(3810),
                            Email = "admin@admin.com",
                            Name = "Admin User",
                            Password = "$2a$11$osLqKY/VW1iLn.bHgiX1xeSNXbN8DpEc1qbX4FMRGumJvTtVqnmQC",
                            PasswordUpdated = new DateTime(2024, 5, 30, 11, 32, 57, 61, DateTimeKind.Utc).AddTicks(3825),
                            Phone = "1234567890",
                            RoleId = 1
                        },
                        new
                        {
                            Username = "user",
                            BirthDate = new DateTime(2004, 5, 30, 11, 32, 57, 338, DateTimeKind.Utc).AddTicks(6720),
                            Email = "user@gmail.com",
                            Name = "User",
                            Password = "$2a$11$oVyFGZFxDUtE/kqz4EzJXODd3h3xmtALymFGhG2Jj7VnRHf7kJ9Fm",
                            PasswordUpdated = new DateTime(2024, 5, 30, 11, 32, 57, 338, DateTimeKind.Utc).AddTicks(6738),
                            Phone = "0987654321",
                            RoleId = 2
                        },
                        new
                        {
                            Username = "user2",
                            BirthDate = new DateTime(2004, 5, 30, 11, 32, 57, 611, DateTimeKind.Utc).AddTicks(9178),
                            Email = "user2@gmail.com",
                            Name = "User2",
                            Password = "$2a$11$hdAWqSD8otkPgF0ReQ6yA.GRLkp7cypLgtxcVZSlY0AeVXfbNRNWK",
                            PasswordUpdated = new DateTime(2024, 5, 30, 11, 32, 57, 611, DateTimeKind.Utc).AddTicks(9195),
                            Phone = "0987654321",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("PartyWebAppServer.Database.Models.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username");

                    b.ToTable("Wallets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 100m,
                            Currency = 1,
                            IsPrimary = false,
                            Username = "user"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 400m,
                            Currency = 2,
                            IsPrimary = false,
                            Username = "user"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 5000m,
                            Currency = 0,
                            IsPrimary = true,
                            Username = "user"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 10000m,
                            Currency = 3,
                            IsPrimary = false,
                            Username = "user"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 10000m,
                            Currency = 0,
                            IsPrimary = true,
                            Username = "user2"
                        });
                });

            modelBuilder.Entity("Repour", b =>
                {
                    b.Property<int>("ProviderId")
                        .HasColumnType("integer");

                    b.Property<string>("Owner")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("ProviderId", "Owner");

                    b.ToTable("Repours");

                    b.HasData(
                        new
                        {
                            ProviderId = 1,
                            Owner = "user",
                            Quantity = 1
                        },
                        new
                        {
                            ProviderId = 2,
                            Owner = "user2",
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("RepourProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("RepourPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("RepourToken")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("RepourProviders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "RepourProvider 1",
                            RepourPrice = 100m,
                            RepourToken = new Guid("12e57abd-4f2e-4374-8191-4740cb495dbd")
                        },
                        new
                        {
                            Id = 2,
                            Name = "RepourProvider 2",
                            RepourPrice = 120m,
                            RepourToken = new Guid("822c7ae0-125a-441c-ae35-1057e7dfb1e1")
                        });
                });

            modelBuilder.Entity("PartyWebAppServer.Database.Models.Event", b =>
                {
                    b.HasOne("PartyWebAppServer.Database.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepourProvider", "RepourProvider")
                        .WithMany()
                        .HasForeignKey("RepourProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("RepourProvider");
                });

            modelBuilder.Entity("PartyWebAppServer.Database.Models.Transaction", b =>
                {
                    b.HasOne("PartyWebAppServer.Database.Models.Event", "Event")
                        .WithMany("Transactions")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartyWebAppServer.Database.Models.Location", "Location")
                        .WithMany("Transactions")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartyWebAppServer.Database.Models.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Location");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("PartyWebAppServer.Database.Models.Wallet", b =>
                {
                    b.HasOne("PartyWebAppServer.Database.Models.User", "Owner")
                        .WithMany("Wallets")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PartyWebAppServer.Database.Models.Event", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("PartyWebAppServer.Database.Models.Location", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("PartyWebAppServer.Database.Models.User", b =>
                {
                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("PartyWebAppServer.Database.Models.Wallet", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
